[package]
name = "raqote-winit"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.8"
euclid = "0.20" # TODO: Update to 0.22. See: https://github.com/jrmuizel/raqote/pull/153
log = "0.4"
pixels = { path = "../.." }
raqote = { version = "0.8", default-features = false }
winit = "0.24"
winit_input_helper = { git = "https://github.com/rukai/winit_input_helper.git", rev = "254b548fb3a0f2a8287c907dc8524a7530e91069" }
