[package]
name = "raqote-winit"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.8"
euclid = "0.22"
log = "0.4"
pixels = { path = "../.." }
raqote = { git = "https://github.com/avr1254/raqote.git", rev = "fa7f1610c4dffcaeaf06022bc1571bf30c4bd16f", default-features = false }
winit = "0.24"
winit_input_helper = "0.9"
