[package]
name = "conway"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
byteorder = "1.3"
env_logger = "0.8"
getrandom = "0.2"
line_drawing = "0.8"
log = "0.4"
pixels = { path = "../.." }
randomize = "3.0"
winit = "0.24"
winit_input_helper = { git = "https://github.com/rukai/winit_input_helper.git", rev = "254b548fb3a0f2a8287c907dc8524a7530e91069" }
